@startuml
class DescriptorWriter
{
    + DescriptorWriter(DescriptorSetLayout &setLayout, DescriptorPool &pool);

    + DescriptorWriter &WriteBuffer(uint32_t binding, VkDescriptorBufferInfo *bufferInfo);
    + DescriptorWriter &WriteImage(uint32_t binding, VkDescriptorImageInfo *imageInfo);

    + bool Build(VkDescriptorSet &set);
    + void OverWrite(VkDescriptorSet &set);

    - DescriptorSetLayout &r_SetLayout;
    - DescriptorPool &r_Pool;
    - std::vector<VkWriteDescriptorSet> m_Writes;
}
@enduml