@startuml
struct [nested]KeyMappings
{
    int moveLeft = GLFW_KEY_A;
    int moveRight = GLFW_KEY_D;
    int moveForward = GLFW_KEY_W;
    int moveBackward = GLFW_KEY_S;
    int moveUp = GLFW_KEY_E;
    int moveDown = GLFW_KEY_Q;
    int lookLeft = GLFW_KEY_LEFT;
    int lookRight = GLFW_KEY_RIGHT;
    int lookUp = GLFW_KEY_UP;
    int lookDown = GLFW_KEY_DOWN;
}

class KeyboardController
{
    + [nested] struct KeyMappings;

    + KeyMappings m_Keys{};
    + float m_TurnSpeed = 1.5f;
    + float m_MoveSpeed = 3.0f;

    + void MoveInPlaneXZ(GLFWwindow *window, float dt, DivineGameObject &gameObjects);
}
@enduml